be-python-flask Dockerfile make work COPY in any case and LABEL cleanup
opendevstack/ods-quickstarters pull request #481
Opened 2020-11-06 12:15 UTC by gerardcl

When building be-python-flask Dockerfile in OpenShift4 the COPY command as is does not work anymore since the /app folder is not there and either not created automatically.

This is a minor change and does keep backwards compatibility.

We also took the chance to cleanup the LABEL attribute as done already in other quickstarters.

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

2020-11-06 12:17 UTC, clemensutschig requested changes
@gerardcl  - please add the maintainer back

2020-11-06 12:19 UTC, clemensutschig approved these changes

2020-11-06 12:21 UTC, gerardcl commented
@clemensutschig it has been removed as per agreement to clean up LABEL attribute in the quickstarters and keep ownership here -> https://github.com/opendevstack/ods-quickstarters/blob/master/CODEOWNERS

2020-11-06 12:21 UTC, merged

2020-11-07 20:30 UTC, clemensutschig commented
@gerardcl can you take a look why the ci Tests are broken since your Merge.  @georgfedermann

2020-11-08 11:24 UTC, gerardcl commented
@clemensutschig what is being tested so that a `mkdir -p` inside the quickstarter's dockerfile makes the qs tests fail? let's check it tomorrow!

2020-11-08 11:31 UTC, clemensutschig commented
@gerardcl - in the readme of odscore you find the Link to the latest Master build

2020-11-08 11:49 UTC, georgfedermann commented
I see this error message in the latest master build:
    amazon-ebs:     verify-ods-namespace-functional_test.go:31: Execution of nexus test.sh failed at /home/openshift/opendevstack/ods-core/nexus/test.sh:
    amazon-ebs:         StdOut: Skip checking for blobstores. This requires an admin password.
    amazon-ebs:           See help on how to specify the admin-password.
    amazon-ebs:           Alternatively env variable NEXUS_ADMIN_PASSWORD can be set or stored in ods-core.env
    amazon-ebs:         Check for repositories
    amazon-ebs:         Repo 'candidates' is missing
    amazon-ebs:

2020-11-08 11:52 UTC, clemensutschig commented
@georgfedermann ok cool..  can you File a Bug in ods-core against this?

2020-11-08 12:55 UTC, gerardcl commented
I confirm I run the test also with success for be-python-flask qs. Unique issue when running it was that the templating did not substitute the Jenkinsfile.template accordingly so I got a Jenkinsfile like:

```
@Library('ods-jenkins-shared-library@@shared_library_ref@') _

odsComponentPipeline(
  imageStreamTag: 'ods-next/jenkins-agent-python:@agent_image_tag@',
```

and had to be like:

```
@Library('ods-jenkins-shared-library@master') _

odsComponentPipeline(
  imageStreamTag: 'ods-next/jenkins-agent-python:latest',
```

After right change in the test repo of the provisioned qs all went through with success.

But, I suspect this is a bad configuration on my side, maybe?