first version of streamlit quickstarter
opendevstack/ods-quickstarters pull request #892
Opened 2023-02-16 09:18 UTC by sklingel

First version of streamlit quickstarter
(I have created a new PR in favor a cleaner commit history with the recent oauth changes)

Closes #891

Tasks: 
- [x ] Updated documentation in `docs/modules/...` directory
- [ ] Ran tests in `<quickstarter>/testdata` directory

2023-02-16 10:32 UTC, gerardcl requested changes

2023-02-16 14:14 UTC, gerardcl requested changes

2023-02-16 14:14 UTC, gerardcl commented on ds-streamlit/files/tests/calculation/sample_test.py
> +        self.assertEqual(samples.shape[0], 10)
missing end of file line

2023-03-01 09:00 UTC, sklingel commented on ds-streamlit/files/tests/calculation/sample_test.py
> +        self.assertEqual(samples.shape[0], 10)
Fixed by newest commit

2023-03-01 09:59 UTC, gerardcl approved these changes
LGTM! 🚀

2023-03-01 13:21 UTC, merged