WIP; switch from shared statfile location to dedicated
opendevstack/ods-quickstarters pull request #932
Opened 2023-06-21 13:41 UTC by nichtraunzer

This PR enables the AWS quickstarter to store the terraform statefile inside its own account. Processing takes place in the Makefile so no change in the shared library necessary.

Closes #900 

Tasks: 
- [ ] Updated documentation in `docs/modules/...` directory
- [x] Ran tests in `<quickstarter>/testdata` directory

2023-06-21 19:46 UTC, tbugfinder requested changes

2023-06-21 19:46 UTC, tbugfinder commented on inf-terraform-aws/files/.pre-commit-config.yaml
> +  rev: v0.4.2
Please add this also for azure.

2023-06-21 19:46 UTC, tbugfinder commented on inf-terraform-aws/files/Makefile
> +	exit 0
hm either this is a left over or the following lines are no longer needed.

2023-06-21 19:46 UTC, tbugfinder commented on inf-terraform-aws/files/Makefile
> +	bundle exec cinc-auditor exec test/integration/default --no-create-lockfile --no-distinct-exit --input-file ./test/integration/$$profile/files/inputs-from-tfo-stack.yml --target aws://
$$profile is not correct.

2023-06-21 19:46 UTC, tbugfinder commented on inf-terraform-aws/files/test/fixtures/default/random.tf
> -  id       = random_id.id.hex
local.id should be available

2023-06-22 19:39 UTC, nichtraunzer commented on inf-terraform-aws/files/Makefile
> +	bundle exec cinc-auditor exec test/integration/default --no-create-lockfile --no-distinct-exit --input-file ./test/integration/$$profile/files/inputs-from-tfo-stack.yml --target aws://
how this happened?

2023-06-22 19:40 UTC, nichtraunzer commented on inf-terraform-aws/files/test/fixtures/default/random.tf
> -  id       = random_id.id.hex
:facepalm

2023-06-23 09:50 UTC, tbugfinder approved these changes

2023-06-23 09:52 UTC, merged